#!/bin/sh

#### USAGE: call ghc(i) like this:
# $ env TMPDIR=/tmp ghc -XNoCPP -c final-tagless.lhs -pgmL=/home/ggreif/kaleidoscope-regensburg/ggreif/trick1 -optL=-#

echo ${1+"$@"} > /dev/tty

#echo $4 > /dev/tty
#echo $# > /dev/tty
_slast=${!#}
#echo ${_slast} > /dev/tty

/home/ggreif/lib/ghc-7.9.20140415/unlit ${1+"$@"}

awk '/ *#/{print ""}{print}' ${_slast} > ${_slast}X && rm ${_slast} && mv ${_slast}X ${_slast}
